#!/usr/bin/env python3
"""Write FUNCTION-CATALOG.md: every function Ghidra found in unf.exe, with the names and
purposes identified during the reverse engineering.  Unidentified ones keep their FUN_ name
and get a module guess from their segment."""
import sys, re

KNOWN = {
 # ---- Borland C++ 3.x runtime (segment 1000)
 "1000:0000": ("c0 startup", "runtime entry: sets up DS/SS, calls main"),
 "1000:0f28": ("pow", "libm pow(double, double), returns in ST0"),
 "1000:115b": ("ftol", "float/double -> long conversion helper"),
 "1000:14bd": ("exit", "libc exit"),
 "1000:23cf": ("clrscr", "conio clear screen"),
 "1000:23f8": ("textcolor", "conio text colour"),
 "1000:2577": ("cputs", "conio string output"),
 "1000:3f09": ("fgets", "libc"),
 "1000:4232": ("fread", "libc"),
 "1000:4409": ("fwrite", "libc"),
 "1000:14f8": ("N_LXMUL", "32-bit multiply helper: DX:AX * CX:BX"),
 "1000:1558": ("N_LDIV", "signed 32-bit divide (stack args, retf 8)"),
 "1000:155f": ("N_LUDIV", "unsigned 32-bit divide"),
 "1000:1567": ("N_LMOD", "signed 32-bit modulo"),
 "1000:156f": ("N_LUMOD", "unsigned 32-bit modulo"),
 "1000:1606": ("N_LXLSH", "32-bit shift left"),
 "1000:1627": ("N_LXRSH", "32-bit arithmetic shift right"),
 "1000:186d": ("lmul32", "32x32 multiply used by rand()"),
 "1000:18a5": ("srand", "seed = value (32-bit)"),
 "1000:18b6": ("rand", "seed = seed*0x015A4E35+1; return (seed>>16)&0x7fff"),
 "1000:329a": ("int86", "Borland int86(intno, inregs, outregs): INT 10h for the VGA DAC, INT 33h for the mouse"),
 "4000:39c0": ("mouse_detect", "int86(0x33) reset/detect; returns button count or 0"),
 "1000:3cb2": ("atol", "string -> long"),
 "1000:3e07": ("fclose", "libc"),
 "1000:4126": ("fopen", "libc"),
 "1000:44ec": ("fgetc", "libc"),
 "1000:4604": ("itoa", "libc"),
 "1000:4646": ("ltoa", "libc (long -> string)"),
 "1000:4feb": ("strcat", "libc"),
 "1000:5089": ("strcpy", "libc"),
 "1000:50ab": ("strlen", "libc"),
 "1000:2de4": ("farmalloc", "far heap allocation"),
 "1000:359a": ("farmalloc_small", "allocation helper used for menu strings"),
 "1000:489b": ("puts", "libc text output (error messages)"),
 # ---- WORLD module = the recovered UNF.CPP (segment 2000)
 "2000:1ccc": ("section_number3", "floor -> 0-based section index"),
 "2000:1d12": ("section_number_p", "wrapper"),
 "2000:1d23": ("section_number", "current floor's section"),
 "2000:1d35": ("section_number2", "section within the module (0..3)"),
 "2000:1b02": ("shade_palette", "16 darker copies of colours 0..15 for distance shading (16-colour modes)"),
 "2000:2d93": ("get_choice", "wait for a menu key in a range"),
 "2000:2b08": ("mset_gmenu", "fill the 8 menu strings"),
 "2000:309e": ("print_menu_only", "show an 8-line message box"),
 "2000:313a": ("give_hint", "print hint n from UH.BIN"),
 "2000:3bc7": ("allocate_buffers", "farmalloc all the big arrays (monster map, menus)"),
 "2000:3d9b": ("reset_view_caches", "throws away everything cached about the view, so the next frame is drawn from nothing"),
 "2000:41ae": ("compute_weight", "loaded weight = body + armor + weapons (0 with Feather)"),
 "2000:4156": ("Random", "srand(clock()) then random(n)"),
 "2000:4212": ("end_prep_spells", "clears preparation-spell effects (called by the inn)"),
 "2000:428d": ("store_refund", "children-helped refund on stock/crystal purchases"),
 "2000:438f": ("show_money", "prints rubles after a purchase"),
 "2000:45ab": ("g_store", "general store"),
 "2000:4d39": ("temple", "temple menu"),
 "2000:4fe7": ("flea_inn", "inn: room price, aging, SP refill, level up"),
 "2000:568b": ("bank", "bank menu"),
 "2000:5c0d": ("select_player", "character-select screen"),
 "2000:620f": ("main", "game main loop"),
 "2000:6573": ("which_monster", "monster index at (x, y)"),
 "2000:65b0": ("monster_at", "the slot of the monster standing on a square, or -1 when it is empty"),
 "2000:65dc": ("set_monster_map", "write the 80x110 occupancy map"),
 "2000:65f8": ("get_mtype", "random monster type for stocking"),
 "2000:671e": ("stock_level", "populate a floor with 145 monsters (boss placement)"),
 "2000:7687": ("load_level_map", "load/stock the monster array for a floor"),
 "2000:7b48": ("exp_needed", "250*1.4^(l-1)-80 / 250*2^(l-1)"),
 "2000:7c71": ("check_gain_level", "exp > exp_needed(lev)?"),
 "2000:7d23": ("gain_level", "apply level-ups"),
 "2000:7e36": ("strike", "player attack roll"),
 "2000:82b7": ("defend", "monster attack roll + drains/poison/disease"),
 "2000:8189": ("gain_or_drain", "moves one of the six stats by a point, the stat picked by the size of -6..-1 / 1..6"),
 "2000:9cba": ("trapdoor", "trap door destination for a square"),
 "2000:a0c8": ("check_engagement", "monster in front of the player?"),
 "2000:a1b7": ("tick_spell_timers", "decrement battle-spell timers"),
 "2000:a319": ("call_check_eng", "engagement in all four directions"),
 "2000:a53c": ("pass_moment", "one game moment: disease/poison, monster movement"),
 "2000:aa95": ("draw_ladder_prompt", "HIT U/D box with the ladder picture"),
 "2000:b5ea": ("detect_chute", "chute destination"),
 "2000:ba3f": ("dig_hole", "'DIGGING... DIGGING...': dig through a wall/floor"),
 "2000:5f78": ("decode_quit_message", "un-Caesars (+2, ` = space) the hidden 'PLEASE DO NOT DISTRIBUTE THIS GAME'"),
 "2000:60e8": ("show_registration_notice", "prints the file 'v' in yellow text mode, waits for a key, 5-way checksum vs constants; mismatch sets the tamper flag -> main exits"),
 "2000:bd32": ("town_features", "store/temple/bank/inn at (x, y)"),
 "2000:bda6": ("trapdoor_dest", "landing square of a trap door"),
 "2000:c22d": ("retdwall2", "retdwall + module teleporters"),
 "2000:c308": ("movecontrol", "the giant keyboard/movement/turn loop"),
 "2000:e017": ("cast_a_spell", "spell/scroll/wand/paper menus, SP accounting"),
 "2000:df3e": ("print_spell_line", "one line of the spell menu"),
 "2000:3654": ("load_overlay_pic", "loads OVERLAY.PIC (the water overlay) into the picture table"),
 "2000:372c": ("load_section_pictures", "loads UFMON<n>.PIC / UFWALL<n>.PIC for a section (name tables DS:02c5 / DS:02ef); sets the water flag for sections 4, 8, 20"),
 "2000:5fec": ("load_md_bin", "reads section records from MD.BIN: 5x29-byte monsters, 4 and 20 40-char text lines each"),
 "2000:702e": ("save_monster_map", "writes <letter>MON.MAP ('wb') at quit"),
 "2000:70f4": ("load_monster_map", "reads <letter>MON.MAP; if missing, stock_level() populates the floor"),
 "2000:7313": ("save_maps", "writes <letter><module><n>.DUN ('wb'); called on floor change, quit and death"),
 "2000:74ae": ("load_maps", "reads <letter><module><n>.DUN ('rb')"),
 "2000:787d": ("load_unfdung_bin", "fread(25 x 512 bytes) of the wall patterns into DS:8680"),
 "2000:78b4": ("load_player", "itoa(slot) file name, fread 0xa87 bytes into pc (DS:b880); 'Corrupted Character! Sorry!' on bad checksum"),
 "2000:79ad": ("save_player", "itoa(slot) file name, fwrite 0xa87 bytes; called by defend, pass_moment, chute, change_module, quit, roll_char"),
 "2000:7a78": ("read_spell_help", "reads entry n from USPELLS.HLP"),
 "2000:9c13": ("quit_game", "Q: save monster map, maps, player; prints the decoded 'PLEASE DO NOT DISTRIBUTE' line; exit"),
 "2000:c0a5": ("change_module", "the module teleporter: next/previous module menu (normal difficulty may not enter Module V), saves maps, floor = 0, relocate() into the new town, saves the player"),
 "2000:c069": ("module_installed", "fopen() test on the module's first UFMON picture file"),
 "2000:b202": ("use_magic_item", "U key: rings/stones/cups/balls"),
 "2000:b532": ("chute", "fall-through message + landing, saves the player"),
 "2000:be3d": ("explain_trapdoor", "the trap door explanation box"),
 "2000:92b1": ("view_prep_spells", "lists active preparation spells"),
 "2000:9417": ("view_battle_spells", "lists active battle spells"),
 "2000:98b7": ("lose_item", "an item is destroyed/lost message"),
 "2000:b68d": ("print_battle_hp_info", "HP/monster line during battle"),
 "2000:90be": ("load_level_screen", "'LOADING... PLEASE WAIT' wrapper around the level loader"),
 "2000:8f99": ("null_check", "null-pointer guard on a far pointer"),
 "2000:b782": ("engagement_timing", "probable: monster engagement timer"),
 "2000:b8f7": ("attack_timing", "probable: attack interval timer"),
 "2000:b1b7": ("move_seconds", "seconds one step costs: a second, plus one per 100 of weight over 10x agility"),
 # ---- TOWN + MAGICFNC + CAT modules (segment 3000)
 "3000:0f75": ("draw_3d_view", "the corridor view (walls, doors, monsters)"),
 "3000:2848": ("draw_map_square", "expanded-map square drawing"),
 "3000:4a24": ("read_uroll_line", "reads the next line of UROLL.TXT, dropping every '|'"),
 "3000:4a67": ("show_rolled_character", "draws the rolled character's numbers, or rubs them out again"),
 "3000:4c77": ("roll_char", "character creation (stats, HP/SP, money)"),
 "3000:5fda": ("design_char", "redistribute points screen"),
 "3000:6c6b": ("set_16_colours", "BIOS palette for 16-colour modes"),
 "3000:6c9d": ("boss_office_message", "'A MESSAGE FROM THE OFFICE OF' screen with the boss picture"),
 "3000:6e85": ("random_events_tick", "the per-step tick: the boss office message every 250 steps, then the random hints and events"),
 "3000:77e2": ("view_stats", "the V screen"),
 "3000:7c6d": ("read_help_screen", "reads one <n>.uhp help screen, the F1 help the game shows a page at a time"),
 "3000:81ba": ("myrand", "the dungeon hash"),
 "3000:827f": ("check_for_ladder", "up/down ladder at a square"),
 "3000:8360": ("retdwall", "wall/door/secret/open for one side"),
 "3000:8432": ("draw_side", "draws one side on the map"),
 "3000:86b5": ("solidcheck", "square is rock?"),
 "3000:87de": ("drawsquare", "draws one explored square with ladder/trap door glyphs"),
 "3000:931c": ("tablet_message", "the stone-tablet text box"),
 "3000:955f": ("level_up_screen", "shows the new level"),
 "3000:99bf": ("title_screen", "the opening title picture"),
 "3000:a023": ("show_spell_help", "spell help viewer (reads USPELLS.HLP)"),
 "3000:968b": ("load_picture_seq", "load a picture sequence and draw"),
 "3000:974d": ("load_building_picture", "load & draw the 4-layer town pictures"),
 "3000:a0fa": ("exp_value", "XP for a kill: (exp+1)*(L+1+5*1.23^L)"),
 "3000:a1fc": ("drop_weapon", "weapon drop roll"),
 "3000:a3d7": ("drop_armor", "armor drop roll"),
 "3000:a5cc": ("spell_name_to_menu", "formats a spell name"),
 "3000:a65d": ("drop_spellbook", "spell book learn roll"),
 "3000:a870": ("drop_scroll", "scroll roll"),
 "3000:aa37": ("drop_wand", "wand roll"),
 "3000:ac6f": ("drop_paper", "spell paper roll"),
 "3000:ae27": ("find_item", "the 12 'YOU FIND' items"),
 "3000:afc5": ("post_kill_heal", "1/4 chance cup of health"),
 "3000:b063": ("post_kill_sp", "1/6 chance ball of thought"),
 "3000:b12d": ("kill_monster", "XP, drainer bonus, drops, boss rewards"),
 "3000:bd9a": ("go_up_level", "HP/SP gain per class"),
 "3000:c093": ("go_down_level", "HP/SP loss on level drain"),
 "3000:c39d": ("monster_manual", "section intro + monster descriptions (S key)"),
 "3000:d0c1": ("msg_no_monster", "'there is no monster' message"),
 "3000:d0ee": ("msg_already_in_effect", "spell already active message"),
 "3000:d11b": ("msg_already_cast_this_spell", "the other 'already cast' refusal"),
 "3000:d148": ("enchant_weapon_perm", "set a weapon's plus"),
 "3000:d211": ("enchant_armor_perm", "set an armor's plus"),
 "3000:d2da": ("set_temp_armor_plus", "prep enchant armor (refuses if not better)"),
 "3000:d2fc": ("set_temp_weapon_plus", "prep enchant weapon"),
 "3000:d31e": ("set_body_armor", "body armor spell"),
 "3000:d340": ("set_prot_ring", "ring of protection spell"),
 "3000:d362": ("set_anti_magic_ring", "anti-magic ring spell (never read by the game)"),
 "3000:d384": ("write_scroll_or_wand", "scroll/wand creation menus"),
 "3000:d7be": ("msg_you_feel_good", "what a small cure prints"),
 "3000:d7eb": ("msg_you_feel_very_good", "what a big cure or a stat boost prints"),
 "3000:d818": ("explosion", "minor/normal/major explosion damage"),
 "3000:d904": ("sleep_monster", "rand(ML) < 3 -> 25 moves"),
 "3000:d990": ("strength", "+7 STR for 60 moves"),
 "3000:d9ba": ("speed", "+7 AGI for 60 moves"),
 "3000:d9e4": ("strength_and_speed", "both boosts at once, each extended by 60 moves if it is already running"),
 "3000:da2c": ("relocate", "random non-rock, unoccupied square (x 0..78, y 0..103); also used by change_module and by Fighters digging too deep"),
 "3000:dab7": ("boss_immune_check", "'NO, THAT SILLY SPELL DOESN'T WORK ON ME'"),
 "3000:db1e": ("go_away", "teleports the monster"),
 "3000:dc18": ("autokill", "the autokill roll"),
 "3000:dd37": ("msg_sixty_moves_longer", "re-casting extended the spell by 60 moves"),
 "3000:dd64": ("power_weapon", "Power Weapon I to III: sets the power-weapon level (save 0x7e8) and its 60-move clock"),
 "3000:ddc9": ("protection", "Minor/Major/Ultra Protection: sets the protection level and its 60-move clock"),
 "3000:de2e": ("resist_poison", "60 moves"),
 "3000:de65": ("resist_disease", "60 moves"),
 "3000:de9c": ("anti_cold", "60 moves"),
 "3000:ded3": ("anti_fire", "60 moves"),
 "3000:df0a": ("resist_drain", "60 moves"),
 "3000:df41": ("drain_monster", "level -= wis or kill"),
 "3000:e003": ("pass_wall", "moves the player through a wall"),
 "3000:e1b8": ("spell_effect", "the big switch: every spell's effect"),
 # ---- DISP module (segment 4000)
 "4000:0abf": ("load_font", ".FNT loader"),
 "4000:0bb3": ("pfont", "print text at x,y"),
 "4000:0db8": ("psfont", "print text with wrapping"),
 "4000:0fc0": ("gmode", "set graphics mode"),
 "4000:102d": ("set_ega_colour", "one of the 16 base colours"),
 "4000:10c2": ("apply_palette", "send the 256-entry palette to the DAC"),
 "4000:1150": ("gradient_palette", "entries 96..255 ramps per section"),
 "4000:12c3": ("set_palette", "builds the whole palette for the current section/building"),
 "4000:2a36": ("fill_rect", "solid rectangle"),
 "4000:4818": ("scale_image2", "draws a .PIC image scaled into a rectangle"),
 "4000:55b2": ("typed_name", "reads a typed string into a buffer: letters, digits and the space bar, backspace, Enter or Escape"),
 "4000:5a87": ("num_to_string", "sprintf-like number formatting"),
 "4000:6aca": ("drop_money", "Greater American Dollars on a kill"),
 "4000:751b": ("shareware_plea_screen", "the 'DELETE THE FILE INTRO.TXT' shareware screen; no callers in the registered build (dead code)"),
 "4000:771b": ("module_transition_screen", "shown by change_module"),
 "4000:42b4": ("erase_menu_block", "clears the menu area"),
 "4000:430e": ("erase_message_block", "clears the message line"),
 "4000:418d": ("mgetch_message", "wait for a key in the message box"),
 "5000:07eb": ("draw_line", "Bresenham line in planar video memory"),
}

GUESS = {"1000": "Borland runtime / libc", "2000": "WORLD (UNF.CPP)", "3000": "TOWN / MAGICFNC / CAT",
         "4000": "DISP (graphics)", "5000": "DISP low-level", "5110": "DISP low-level", "5120": "video drivers", "5400": "video drivers"}

rows = []
for line in open(sys.argv[1]):
    addr, name, size, callers = line.rstrip('\n').split('\t')
    seg = addr[:4]
    k = KNOWN.get(addr)
    rows.append((addr, k[0] if k else name, size.replace('size=', ''), (k[1] if k else ''), GUESS.get(seg, ''), callers.replace('callers=', '')))
out = ["# Function catalog for unf.exe (1993 registered build, page-relaid Ghidra layout)", "",
       "Addresses are Ghidra's view of the re-laid-out executable: segment 1000 = Borland runtime,",
       "2000 = WORLD (the recovered UNF.CPP), 3000 = TOWN/MAGICFNC/CAT, 4000/5000+ = DISP and video",
       "drivers, 6000 = data.  %d functions; %d identified.  Names are ours, not the original symbols,"
       % (len(rows), sum(1 for r in rows if r[3])),
       "except where UNF.CPP gave them.  See METHOD.md for how the identifications were made.", "",
       "| address | name | size | purpose | module | callers |", "|---|---|---:|---|---|---|"]
for addr, name, size, purpose, mod, callers in rows:
    c = callers.split(',') if callers else []
    cs = ', '.join(KNOWN.get(x.replace('FUN_', '').replace('_', ':'), (x,))[0] if x.startswith('FUN_') else x for x in c[:6]) + (' …' if len(c) > 6 else '')
    out.append("| %s | %s | %s | %s | %s | %s |" % (addr, name, size, purpose, mod, cs))
open(sys.argv[2], 'w').write("\n".join(out) + "\n")
print("catalog:", len(rows), "functions,", sum(1 for r in rows if r[3]), "identified")
