-- Who may use the admin endpoints.
--
-- It is a flag on the player rather than a table of its own: an admin is a player like any other,
-- with a name, characters and a passphrase, who is also allowed to delete anybody's character.
-- Nobody has it until the server is told who to give it to, so a fresh database has no admin at
-- all and every endpoint is what it was before this.
--
-- `ADMIN_PLAYER` names the player whose row is flagged at start (server/admins.ts), which is how
-- John is recognised on a new deploy without anybody opening the database; an admin flags another
-- player through the endpoint.
ALTER TABLE players ADD COLUMN admin boolean NOT NULL DEFAULT false;

-- Every admin action, written down as it is done.
--
-- An admin deletes other people's characters for good, and this row is what is left afterwards to
-- say so: who did it, what they did and what they did it to.
--
-- `about` is the thing acted on, named the way the action itself names it -- the character's id
-- for a deletion, the name for a player flagged. These rows are read by eye rather than joined
-- against anything, and the thing acted on may not be there any more to join to.
CREATE TABLE admin_actions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_id integer NOT NULL REFERENCES players(id),
  action text NOT NULL,
  about text NOT NULL,
  at timestamptz NOT NULL DEFAULT now()
);
