-- The endless worlds there have been, one row apiece, the newest being the one every endless
-- character rolled now is rolled into.
--
-- A world is one number, and two characters rolled into the same one meet the same monsters on
-- the same floor. Nothing changes it on a schedule: the admin sets a new world when a fresh one
-- is wanted, and every character already rolled keeps the world it was rolled into, so the world
-- before is still played and still has boards of its own.
--
-- It is a row rather than a column written over, because the worlds that were played before are
-- what their characters' boards are read for, and when each was set and who set it is the whole
-- history of the dungeon. Nothing is ever taken out.
--
-- `set_by` is the admin who set it, and null for this first one, which nobody set: it is world 1,
-- the world every endless character rolled before this was rolled into (`ENDLESS_WORLD_SEED` in
-- src/lib/game/endless/rules.ts), so that a character rolled yesterday stands on the board of the
-- world it was really played in.
CREATE TABLE worlds (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  seed bigint NOT NULL,
  set_at timestamptz NOT NULL DEFAULT now(),
  set_by integer REFERENCES players(id)
);

INSERT INTO worlds (seed) VALUES (1);
